name: edman_cli Unittest

on:
  push:
    branches: [ develop ]

jobs:
  edman_cli_unittest:
    runs-on: ubuntu-latest

    steps:
      # Equivalent to 'actions/checkout@v6.0.2'
      - name: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # Equivalent to 'actions/setup-python@v6.2.0'
      - name: setup python and sources
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'
          check-latest: true
      - run: python -m venv venv
      - run:  source ./venv/bin/activate
      - run:  pip install -U pip setuptools
      - run:  pip install pytest mypy flake8
      - run:  pip install .
      - run:  cp ./tests/ini/test_db.ini.sample ./tests/ini/test_db.ini

      - name: run pytest
        run: |
          cd ./tests
          pytest

      - name: run mypy
        run: |
          mypy ./scripts

      - name: run flake8
        run: |
          flake8 ./scripts
          
